# -*- coding: utf-8 -*-
"""Fibonacci.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YBuObkQvsyO7lfo8F_Qtw3268FT4mAqz
"""

num_repetitions = int(input("Enter the number of repetitions for the Fibonacci sequence: "))

if num_repetitions <= 0:
    print("Please enter a positive integer.")
elif num_repetitions == 1:
    fib_sequence = [0]
elif num_repetitions == 2:
    fib_sequence = [0, 1]
else:
    fib_sequence = [0, 1]
    while len(fib_sequence) < num_repetitions:
        next_fib = fib_sequence[-1] + fib_sequence[-2]
        fib_sequence.append(next_fib)

print("Fibonacci Sequence:", fib_sequence)